# 例外處理
- try：一個try塊標識了一個將被攔截的特定的異常的程式區塊。後跟一個或多個catch區塊。
- catch：程序通過例外處理程序攔截例外。catch關鍵字表示例外的攔截。
- finally：finally區塊用於執行給定的語句，不管例外是否被拋出都會執行。例如，如果您打開一個文件，不管是否出現異常文件都要被關閉。
- throw：當問題出現時，程式拋出一個例外。使用throw關鍵字來完成。

```C#
try
{
   //引起異常的語句
}
catch ( ExceptionName e1 )
{
   //錯誤處理代碼
}
catch ( ExceptionName e2 )
{
   //錯誤處理代碼
}
catch ( ExceptionName eN )
{
   //錯誤處理代碼
}
finally
{
   //要執行的語句
}

int GetInt(int[] array, int index)
{
    try
    {
        return array[index];
    }
    catch(IndexOutOfRangeException e)
    {
        //TODO
    }
}
```
---
# 例外狀況的最佳做法
設計良好的應用程式可處理例外狀況和錯誤，防止應用程式損毀。
## 使用 try/catch/finally 區塊從錯誤中復原或釋放資源  
在可能產生例外狀況的程式碼周圍使用 try/catch 區塊，「且」 您的程式碼即可從該例外狀況復原。 在 catch 區塊中，一律將例外狀況從最具衍生性的排列到最不具衍生性。 所有例外狀況皆衍生自 Exception。 前有基底例外狀況類別 catch 子句的 catch 子句，不會處理最具衍生性的例外狀況。 當您的程式碼無法從例外狀況復原時，請不要攔截該例外狀況。 如果可能，請啟用方法讓呼叫堆疊盡可能修復。
清除配置了 using 陳述式或 finally 區塊的資源。 擲回例外狀況時，偏好使用 using 陳述式來自動清除資源。 使用 finally 區塊清除不會實作 IDisposable 的資源。 就算擲回例外狀況，也一律執行 finally 子句中的程式碼。
## 處理常見的狀況，而不擲回例外狀況
針對可能發生但可能會觸發例外狀況的狀況，請考慮以避免例外狀況的方式來處理這些狀況。 例如，如果您嘗試關閉已關閉的連線，您會得到 InvalidOperationException。 您可以在嘗試關閉之前，使用 if 陳述式來檢查連線狀態，以避免此例外狀況。
```C#
try
{
    conn.Close();
}
catch (InvalidOperationException ex)
{
    Console.WriteLine(ex.GetType().FullName);
    Console.WriteLine(ex.Message);
}

if (conn.State != ConnectionState.Closed)
{
    conn.Close();
}
```
選擇的方法取決於您預期事件會發生的頻率。
- 如果事件不常發生，也就是說事件真的是例外並且表示錯誤 (例如未預期的檔案結尾)，則使用例外狀況處理。 當您使用例外狀況處理時，在正常情況下會執行較少的程式碼。
- 如果事件定期發生而且可視為正常執行的一部分，請檢查程式碼中是否有錯誤狀況。 當您檢查是否有常見的錯誤狀況時，因為避免例外狀況，所以會執行較少的程式碼。  

另一個避免例外狀況的方法是針對很常見的錯誤案例傳回 Null (或預設值)，而不擲回例外狀況。 相當普遍的錯誤案例可視為一般控制流程。 針對這些案例傳回 Null (或預設值)，就能盡量降低對應用程式效能的影響。
## 擲回例外狀況來代替傳回錯誤碼
例外狀況可確保不會發生未通知失敗的情況，因為呼叫程式碼並不會檢查傳回碼。  
## 使用預先定義的 .NET 例外狀況類型
只有在預先定義的類型不適用時，才引進新的例外狀況類別。 例如：
- 如果屬性集或方法呼叫對於物件的目前狀態而言並不適當，就會擲回 InvalidOperationException 例外狀況。
- 在傳遞的參數無效時擲回 ArgumentException 例外狀況，或擲回預先定義之類別中，從 ArgumentException 衍生而來的類別。
## 放置 throw 陳述式讓堆疊追蹤更有用
堆疊追蹤會從擲回例外狀況所在的陳述式開始，並在攔截例外狀況的 catch 陳述式結束。
## 當方法因為例外狀況而未完成時還原狀態
呼叫端應該能夠假設，從方法擲回例外狀況時不會產生副作用。 例如，如果您有用來轉帳的程式碼，會從某個帳戶提款再存入另一個帳戶，而且在執行存款時擲回例外狀況，則您不想要讓提款仍有效。
```C#
public void TransferFunds(Account from, Account to, decimal amount)
{
    from.Withdrawal(amount);
    // If the deposit fails, the withdrawal shouldn't remain in effect.
    to.Deposit(amount);
}
```
上述的方法不直接擲回任何例外狀況，但必須以自我防禦的方式寫入，以便存款作業失敗時可以撤銷付款。
處理這種情況的一個方式是攔截存款交易所擲回的任何例外狀況，並復原提款。
```C#
private static void TransferFunds(Account from, Account to, decimal amount)
{
    string withdrawalTrxID = from.Withdrawal(amount);
    try
    {
        to.Deposit(amount);
    }
    catch
    {
        from.RollbackTransaction(withdrawalTrxID);
        throw;
    }
}
```